package com.chess.game;

public enum GameStatus {
    AGAIN,
    PAWN_PROMOTION,
    CONTINUE,
    CHECKMATE,
    ABSTENTION,
    STALEMATE,
    LACK_OF_CHESS_PIECES,
    FIFTY_MOVE_RULE,
    THREE_ISOMORPHIC_REPETITIONS
}
